# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Get current directory
      run: echo ${{ github.workspace }}
    - name: Restore dependencies
      run: dotnet restore  
      working-directory: ${{ github.workspace }}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ github.workspace }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ github.workspace }}
